import type { ReactNode } from 'react';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import portrait from '@/assets/shivam-portrait.png.asset.json';
import data from '@/data/portfolio.json';
import { PortfolioNavigation, PortfolioProjects, PortfolioSkills, PortfolioContactForm } from './PortfolioControls';

function Section({id,number,label,title,children}:{id:string;number:string;label:string;title:string;children:ReactNode}) {
  return <section id={id} className="portfolio-section"><div className="section-meta"><span>{number} / {label}</span><span>SHIVAM SINGH</span></div><h2 className="editorial-heading">{title}</h2>{children}</section>;
}

export function Portfolio() {
  return <div className="portfolio"><PortfolioNavigation /><main>
    <section id="home" className="portfolio-hero"><img className="hero-portrait" src={portrait.url} alt="Shivam Singh" fetchPriority="high" /><div className="hero-shade" /><div className="hero-copy"><p className="eyebrow">BRIDGING TECHNOLOGY & TALENT ACQUISITION</p><h1>SHIVAM<br />SINGH</h1><p className="hero-role">Technical Recruiter &<br />Java Full-Stack Developer</p><p className="hero-summary">{data.intro}</p><div className="hero-actions"><Button asChild variant="outline"><a href="#projects">View my projects <ArrowDown /></a></Button><Button asChild variant="link"><a href="#contact">Let's connect <ArrowUpRight /></a></Button></div></div><div className="hero-bottom"><span>Noida, Uttar Pradesh, India</span><span>Open to Software Engineer & Java Full-Stack Developer opportunities</span><a href="#about" aria-label="Scroll to About"><ArrowDown /></a></div></section>
    <div className="portfolio-body">
      <Section id="about" number="01" label="THE PERSON" title="ABOUT ME"><div className="about-layout"><div><p className="lead-copy">{data.about[0]}</p>{data.about.slice(1).map((p) => <p className="body-copy" key={p}>{p}</p>)}<p className="body-copy">{data.heroBio}</p></div><div className="bring"><h3>What I bring</h3>{['Technical & AI Understanding','Full-Stack Java & React Development','US IT & Technical Sourcing','Published AI Research & Problem Solving','Agile Development & SDLC','Continuous Learning & Adaptability'].map((item,i) => <div key={item}><span>0{i+1}</span>{item}</div>)}</div></div><div className="stat-strip">{[['7.5 / 10','B.Tech CSE CGPA'],['1st place','24-hour hackathon'],['JSIAR','Published research'],['US IT','Recruitment experience']].map(([value,label]) => <div key={value}><strong>{value}</strong><span>{label}</span></div>)}</div></Section>
      <Section id="experience" number="02" label="CAREER JOURNEY" title="EXPERIENCE"><div className="experience-list">{data.experience.map((job) => <article className="experience-row" key={job.company}><div><p className="eyebrow">{job.date}</p><h3>{job.title}</h3><p className="company">{job.company}</p><p className="location">{job.location}</p></div><div>{job.summary.map((p) => <p className="body-copy" key={p}>{p}</p>)}<ul>{job.points.map((p) => <li key={p}>{p}</li>)}</ul><div className="technology-list">{job.tags.map((t) => <span key={t}>{t}</span>)}</div></div></article>)}</div></Section>
      <Section id="skills" number="03" label="TECHNICAL & RECRUITMENT" title="SKILLS"><PortfolioSkills /></Section>
      <Section id="projects" number="04" label="SOFTWARE PORTFOLIO" title="SELECTED WORK"><PortfolioProjects /><div className="github-band"><div><h3>Open Source & GitHub</h3><p>Explore my projects, experiments, and development work on GitHub.</p></div><Button asChild variant="outline"><a href={data.socials[0].url} target="_blank" rel="noreferrer">Visit my GitHub <ArrowUpRight /></a></Button></div></Section>
      <Section id="research" number="05" label="RESEARCH & ACHIEVEMENTS" title="BEYOND CODE"><div className="research-publication"><p className="eyebrow">RESEARCH PUBLICATION · JSIAR · MAY 2025</p><h3>{data.research.title}</h3><p className="body-copy">{data.research.description}</p><div className="technology-list">{data.research.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><Button asChild variant="link"><a href={data.research.url} target="_blank" rel="noreferrer">Read published paper on JSIAR <ArrowUpRight /></a></Button></div><div className="achievement-grid">{data.achievements.map((a) => <article key={a.title}><h3>{a.title}</h3><p>{a.description}</p></article>)}</div><div className="difference"><p className="eyebrow">WHY MY BACKGROUND IS DIFFERENT</p><h3>Recruitment + Technology</h3><p>Better tech talent understanding.</p><div className="achievement-grid">{[['Talent & Hiring Insight','Understanding hiring requirements, candidate evaluation, sourcing, screening, and recruitment processes.'],['Engineering Depth','Understanding Java, Spring Boot, React.js, APIs, databases, and software development workflows.'],['Effective Translator','Ability to communicate technical requirements clearly and understand both hiring teams and technical professionals.']].map(([title,description]) => <article key={title}><h4>{title}</h4><p>{description}</p></article>)}</div></div><div className="career-roadmap"><h3>Career Roadmap</h3><div>{[['2022','Started B.Tech','Computer Science'],['2025','Web Dev Intern','Alcronix'],['2025','HR Intern','Better Fly Management'],['2026','US IT Recruiter','Headfield Solutions'],['2026','Tech Recruiter','Droisys'],['Present','Tech + Recruiting','Building Expertise']].map(([year,role,org]) => <article key={role}><span>{year}</span><h4>{role}</h4><p>{org}</p></article>)}</div></div></Section>
      <Section id="education" number="06" label="ACADEMIC FOUNDATION" title="EDUCATION">{data.education.map((edu) => <article className="education-row" key={edu.title}><p className="eyebrow">{edu.text[3]}</p><div><p className="eyebrow">{edu.text[0]}</p><h3>{edu.title}</h3>{edu.text.slice(2).filter((x) => x !== edu.text[3]).map((line) => <p key={line}>{line}</p>)}</div></article>)}</Section>
      <Section id="certifications" number="07" label="VERIFIED CREDENTIALS" title="CERTIFICATIONS">{data.certifications.map((cert) => <article className="certificate-row" key={cert.title}><div><h3>{cert.title}</h3><p>{cert.description}</p></div>{cert.links.map((link) => <Button asChild variant="link" key={link.url}><a href={link.url} target="_blank" rel="noreferrer">{link.label}<ArrowUpRight /></a></Button>)}</article>)}</Section>
      <Section id="contact" number="08" label="LET'S CONNECT" title="GET IN TOUCH"><p className="lead-copy contact-intro">Whether you're hiring, looking for technical talent, or discussing software engineering opportunities, I'd love to connect.</p><div className="contact-layout"><div><a className="contact-email" href="mailto:shivamgovindsingh1@gmail.com">shivamgovindsingh1@gmail.com <ArrowUpRight /></a><a className="contact-phone" href="tel:+919730704061">+91 9730704061</a><p className="body-copy">Noida, Uttar Pradesh, India</p><div className="social-list">{data.socials.map((social) => <a key={social.label} href={social.url} target="_blank" rel="noreferrer">{social.label}<ArrowUpRight /></a>)}</div></div><PortfolioContactForm /></div></Section>
      <footer className="portfolio-footer"><span>© {new Date().getFullYear()} Shivam Singh.</span><span>Built with passion for technology and continuous learning.</span><a href="#home">Back to top ↑</a></footer>
    </div>
  </main></div>;
}